target: models.transformer.basemodel.TrainModel
params:
  ckpath: /work3/s212645/Spectral_Reconstruction/checkpoint/Restormer/
  image_key: 'label'
  # cond_key: 'cond'
  cond_key: 'ycrcb'
  valid_ratio: 0.1
  test_ratio: 0.1
  progressive_train: False
  datanames: ['ARAD/']
  padding_tpye: reflect
  padding_size: 128
  genconfig:
    target: models.transformer.Restormer.Restormer
    params:
      inp_channels: 6
      out_channels: 31