target: models.gan.gan.Gan
params:
  ckpath: /work3/s212645/Spectral_Reconstruction/checkpoint/gan/DTN-SN_Discriminator/
  valid_ratio: 0.1
  test_ratio: 0.1
  genconfig:
    target: models.transformer.DTN
    params:
      in_dim: 6
      out_dim: 31
      img_size: [128, 128]
      window_size: 8
      n_block: [2,2,2,2]
      bottleblock: 4

  disconfig:
    target: models.gan.networks.SN_Discriminator
    params:
      input_nums: 37
      n_layer: 3
      n_block: 1

  lossconfig:
    target: models.losses.gan_loss.Wasserstein_Loss
    params:
      l1_weight: 100.0
      sam_weight: 1.0
      features_weight: 0.0
      deltaE_weight: 1.0
      disc_weight: 0.0
      perceptual_weight: 0.0
      threshold: 0
  
