model:
  base_learning_rate: 4.5e-6
  target: models.transformer.Base.BaseModel
  params:
    epochs: 100
    learning_rate: 4e-04
    cond_key: cond
    modelconfig:
      target: models.transformer.DTN.DTN
      params:
        in_dim: 3
        out_dim: 31
        img_size: [128, 128]
        window_size: 8
        n_block: [2, 2, 2, 2]
        bottleblock: 4 
        
data:
  target: dataset.base.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 32
    train:
      target: dataset.datasets.TrainDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/
        crop_size: 128
        valid_ratio: 0.1
        test_ratio: 0.1
        aug: True
        datanames: ['ARAD/']
    validation:
      target: dataset.datasets.ValidDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/
        crop_size: 128
        valid_ratio: 0.1
        test_ratio: 0.1
        aug: True
        datanames: ['ARAD/']
