path: /work3/s212645/Spectral_Reconstruction/checkpoint/vae/
model:
  target: models.vae.vae.AutoencoderKL
  params:
    image_key: cond
    monitor: "val/mrae_avg"
    embed_dim: 64
    learning_rate: 4.0e-4
    lossconfig:
      target: models.vae.sndiscriminator.SpectralNormalizationWDiscriminator
      params:
        disc_start: 0
        kl_weight: 0.000001
        pixelloss_weight: 10.0
        disc_weight: 0.5
        features_weight: 0.0
        perceptual_weight: 1.0
        deltaE_weight: 0.0
        sam_weight: 0.0
        disc_conditional: False
        losstype: wasserstein
        discconfig: 
          target: models.gan.networks.SN_Densenet201_Discriminator
          params:
            input_nums: 3

    ddconfig:
      double_z: True
      z_channels: 64
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 31
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_attn_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0


data:
  target: dataset.base.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 32
    train:
      target: dataset.datasets.TrainDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/
        crop_size: 256
        valid_ratio: 0.1
        test_ratio: 0.1
        arg: True
        datanames: ['ARAD/']
    validation:
      target: dataset.datasets.ValidDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/
        crop_size: 512
        valid_ratio: 0.1
        test_ratio: 0.1
        arg: False
        datanames: ['ARAD/']

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
