model:
  base_learning_rate: 4.5e-6
  first_stage:
    target: taming.models.vqgan.VQModel
    params:
      embed_dim: 256
      n_embed: 1024
      image_key: "image"
      ddconfig:
        double_z: False
        z_channels: 256
        resolution: 256
        in_channels: 31
        out_ch: 31
        ch: 128
        ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
        num_res_blocks: 2
        attn_resolutions: [16]
        dropout: 0.0

      lossconfig:
        target: taming.modules.losses.vqloss.VQLPIPSWithDiscriminator
        params:
          disc_conditional: False
          disc_in_channels: 31
          disc_start: 0
          disc_weight: 0.8
          codebook_weight: 1.0
  cond_stage:
    target: taming.models.vqgan.VQModel
    params:
      embed_dim: 256
      n_embed: 1024
      image_key: "cond"
      ddconfig:
        double_z: False
        z_channels: 256
        resolution: 256
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
        num_res_blocks: 2
        attn_resolutions: [16]
        dropout: 0.0

      lossconfig:
        target: taming.modules.losses.vqloss.VQLPIPSWithDiscriminator
        params:
          disc_conditional: False
          disc_in_channels: 31
          disc_start: 0
          disc_weight: 0.8
          codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 8
    train:
      target: taming.data.hsi_dataset.TrainDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/
        crop_size: 256
        valid_ratio: 0.1
        test_ratio: 0.1
        aug: True
        datanames: ['ARAD/']
    validation:
      target: taming.data.hsi_dataset.ValidDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/
        crop_size: 256
        valid_ratio: 0.1
        test_ratio: 0.1
        aug: True
        datanames: ['ARAD/']
