model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.FirstStageVQModel
  params:
    learning_rate: 4.0e-4
    embed_dim: 256
    n_embed: 1024
    image_key: "label"
    cond_key: "cond"
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 31
      out_ch: 31
      ch: 128
      ch_mult: [1,2,4,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    condconfig:
      base_learning_rate: 4.0e-4
      target: taming.models.vqgan.CondVQModel
      params:
        ckpt_path: /work3/s212645/Spectral_Reconstruction/checkpoint/vqgan/lightning_logs/version_5/checkpoints/last.ckpt
        learning_rate: 4.5e-6
        embed_dim: 256
        n_embed: 1024
        image_key: "cond"
        ddconfig:
          double_z: False
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1,2,4,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0

        lossconfig:
          target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
          params:
            disc_conditional: False
            disc_in_channels: 3
            disc_start: 0
            disc_weight: 0.8
            codebook_weight: 1.0

    lossconfig:
      target: taming.modules.losses.vqloss.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 31
        disc_start: 0
        disc_weight: 0.8
        codebook_weight: 1.0
        perceptual_weight: 0.0

data:
  target: dataset.base.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 32
    train:
      target: dataset.datasets.TrainDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/
        crop_size: 256
        valid_ratio: 0.1
        test_ratio: 0.1
        aug: True
        datanames: ['ARAD/']
    validation:
      target: dataset.datasets.ValidDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/
        crop_size: 256
        valid_ratio: 0.1
        test_ratio: 0.1
        aug: True
        datanames: ['ARAD/']