target: models.transformer.basemodel.TrainModel
params:
  ckpath: /work3/s212645/Spectral_Reconstruction/checkpoint/DTN/
  image_key: 'label'
  cond_key: 'ycrcb'
  valid_ratio: 0.1
  test_ratio: 0.1
  datanames: ['ARAD/']
  stride: 128
  random_split_data: True
  progressive_train: True
  genconfig:
    target: models.transformer.DTN
    params:
      in_dim: 6
      out_dim: 31
      img_size: [128, 128]
      window_size: 8
      n_block: [2, 4]
      bottleblock: 4 
      num_msab: 1
      use_conv: False
      use_cswin: False
      use_gdfn: False