target: models.gan.gan.Gan
params:
  ckpath: /work3/s212645/Spectral_Reconstruction/checkpoint/gan/DTN_multi_stage-SN_Discriminator/
  valid_ratio: 0.1
  test_ratio: 0.1
  genconfig:
    # target: models.transformer.SN_DTN
    target: models.transformer.DTN_multi_stage
    params:
      in_channels: 6
      out_channels: 31
      n_feat: 31
      stage: 3
      img_size: [128, 128]

  disconfig:
    target: models.gan.networks.SN_Discriminator
    params:
      input_nums: 37
      n_layer: 3
      n_block: 1

  lossconfig:
    target: models.losses.gan_loss.Wasserstein_Loss
    params:
      l1_weight: 40.0
      sam_weight: 1.0
      features_weight: 0.0
      disc_weight: 0.0
      perceptual_weight: 1.0
      threshold: 0
  
