model:
  target: models.gan.sncwgan.SpectralNormalizationCGAN
  params:
    logdir: /work3/s212645/Spectral_Reconstruction/checkpoint/SwinGAN/DT_attn-SNTransformerDiscriminator/
    epochs: 101
    learning_rate: 2e-04
    cond_key: ycrcb
    monitor: 'val/mrae_avg'
    modelconfig:
      target: models.transformer.DT_attn.DTN
      params:
        in_dim: 6
        out_dim: 31
        img_size: [128, 128]
        window_size: 8
        n_block: [2, 4]
        bottleblock: 4 
        num_msab: 1
        use_conv: False
        use_cswin: True
        use_gdfn: True
    disconfig:
      target: models.gan.networks.SNDualTransformerDiscriminator
      params:
        input_nums: 37
        n_block: [2,2,2]

    lossconfig:
      target: models.losses.gan_loss.Loss
      params:
        l1_weight: 10.0
        sam_weight: 0.1
        features_weight: 0.0
        deltaE_weight: 1.0
        disc_weight: 0.0
        perceptual_weight: 0.0
        threshold: 1
        losstype: wasserstein
        padding_type: reflect

data:
  target: dataset.base.DataModuleFromConfig
  params:
    batch_size: 40
    num_workers: 32
    train:
      target: dataset.datasets.TrainDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/
        crop_size: 128
        valid_ratio: 0.1
        test_ratio: 0.1
        arg: True
        datanames: ['ARAD/']
    validation:
      target: dataset.datasets.ValidDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/
        crop_size: 512
        valid_ratio: 0.1
        test_ratio: 0.1
        arg: False
        datanames: ['ARAD/']
