model:
  target: models.transformer.Base.BaseModel
  params:
    epochs: 500
    logdir: /work3/s212645/Spectral_Reconstruction/checkpoint/SST_CAT/
    learning_rate: 1e-04
    cond_key: ycrcb
    monitor: 'val/mrae_epoch'
    modelconfig:
      target: models.transformer.SST_CAT.SSTransformer
      params:
        in_dim: 6
        out_dim: 31
        split_size: 1
        input_resolution: [128, 128]
        n_blocks: [2, 2]
        bottle_depth: 2
        n_refine: 2
        patch_size: 8

data:
  target: dataset.base.DataModuleFromConfig
  params:
    batch_size: 40
    num_workers: 32
    train:
      # target: dataset.datasets.TrainDataset
      target: dataset.hsi_dataset.TrainDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/dataset/ARAD/
        crop_size: 128
        arg: True
        stride: 64
        one: False
    validation:
      # target: dataset.datasets.ValidDataset
      target: dataset.hsi_dataset.ValidDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/dataset/ARAD/
        one: False
