model:
  target: models.transformer.Base.BaseModel
  params:
    logdir: /work3/s212645/Spectral_Reconstruction/checkpoint/SST_Multi_Stage/
    epochs: 101
    learning_rate: 2e-04
    cond_key: cond
    monitor: 'val/mrae_epoch'
    modelconfig:
      target: models.transformer.SST.SST_Multi_Stage
      params:
        in_dim: 3
        out_dim: 31
        split_size: 1
        input_resolution: [128, 128]
        patch_size: 8
        stage: 3

data:
  target: dataset.base.DataModuleFromConfig
  params:
    batch_size: 40
    num_workers: 32
    train:
      target: dataset.datasets.TrainDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/
        crop_size: 128
        valid_ratio: 0.1
        test_ratio: 0.1
        arg: True
        datanames: ['ARAD/']
    validation:
      target: dataset.datasets.ValidDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/
        crop_size: 512
        valid_ratio: 0.1
        test_ratio: 0.1
        arg: False
        datanames: ['ARAD/']
