target: models.transformer.basemodel.TrainModel
params:
  ckpath: /work3/s212645/Spectral_Reconstruction/checkpoint/SSTransformer/
  image_key: 'label'
  cond_key: 'cond'
  # cond_key: 'ycrcb'
  valid_ratio: 0.1
  test_ratio: 0.1
  progressive_train: False
  datanames: ['ARAD/']
  padding_tpye: reflect
  padding_size: 128
  genconfig:
    target: models.transformer.SST.SSTransformer
    params:
      in_dim: 3
      out_dim: 31
      split_size: 1
      input_resolution: [128, 128]
      n_blocks: [2, 2]
      bottle_depth: 2
      n_refine: 2
      patch_size: 8
  data:
    target: dataset.base.DataModuleFromConfig
    params:
      batch_size: 40
      num_workers: 32
      train:
        target: dataset.datasets.TrainDataset
        params:
          data_root: /work3/s212645/Spectral_Reconstruction/
          crop_size: 128
          valid_ratio: 0.1
          test_ratio: 0.1
          arg: True
          datanames: ['ARAD/']
      validation:
        target: dataset.datasets.ValidDataset
        params:
          data_root: /work3/s212645/Spectral_Reconstruction/
          crop_size: 512
          valid_ratio: 0.1
          test_ratio: 0.1
          arg: False
          datanames: ['ARAD/']
