target: models.transformer.basemodel.TrainModel
params:
  ckpath: /work3/s212645/Spectral_Reconstruction/checkpoint/sstransformer_ori_64/
  image_key: 'label'
  cond_key: 'cond'
  # cond_key: 'ycrcb'
  valid_ratio: 0.053
  test_ratio: 0.0
  datanames: ['ARAD-origin/']
  random_split_data: False
  stride: 64
  padding_size: 128
  progressive_train: False
  val_in_epoch: True
  
  genconfig:
    target: models.transformer.SST.SSTransformer
    params:
      in_dim: 3
      out_dim: 31
      split_size: 1
      input_resolution: [128, 128]
      n_blocks: [2, 2]
      bottle_depth: 2
      n_refine: 2
      patch_size: 8