model:
  base_learning_rate: 5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    learning_rate: 4.0e-4
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "cond"
    image_size: 64
    channels: 64
    cond_stage_trainable: False
    concat_mode: True
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 128
        out_channels: 64
        model_channels: 192
        attention_resolutions: [ 8,4,2 ]   # 32, 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1,2,4,4 ]  # 32, 16, 8, 4, 2
        num_heads: 32

    first_stage_config:
      base_learning_rate: 4.5e-6
      target: ldm.models.autoencoder.FirstStageAutoencoderKL
      params:
        learning_rate: 4.0e-4
        image_key: image
        cond_key: cond
        monitor: "val/rec_loss"
        embed_dim: 64
        ckpt_path: "/work3/s212645/Spectral_Reconstruction/checkpoint/ldm/ae/logs/2024-03-25T10-48-12_hsi_autoencoder_kl/checkpoints/last.ckpt"
        lossconfig:
          target: ldm.modules.losses.LPIPSWithDiscriminator
          params:
            disc_in_channels: 31
            disc_start: 50001
            kl_weight: 0.000001
            disc_weight: 0.5
            perceptual_weight: 0

        condconfig: 
          base_learning_rate: 4.5e-6
          target: ldm.models.autoencoder.CondAutoencoderKL
          params:
            learning_rate: 4.0e-4
            image_key: cond
            monitor: "val/rec_loss"
            ckpt_path: "/work3/s212645/Spectral_Reconstruction/checkpoint/ldm/cond/logs/2024-03-24T19-57-56_hsi_autoencoder_kl_cond/checkpoints/last.ckpt"
            embed_dim: 64
            lossconfig:
              target: ldm.modules.losses.LPIPSWithDiscriminator
              params:
                disc_in_channels: 3
                disc_start: 50001
                kl_weight: 0.000001
                disc_weight: 0.5
                perceptual_weight: 0

            ddconfig:
              double_z: True
              z_channels: 64
              resolution: 256
              in_channels: 3
              out_ch: 3
              ch: 128
              ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
              num_res_blocks: 2
              attn_resolutions: [ ]
              dropout: 0.0

        ddconfig:
          double_z: True
          z_channels: 64
          resolution: 256
          in_channels: 31
          out_ch: 31
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0

    cond_stage_config:
      base_learning_rate: 4.5e-6
      target: ldm.models.autoencoder.CondAutoencoderKL
      params:
        learning_rate: 4.0e-4
        image_key: cond
        monitor: "val/rec_loss"
        ckpt_path: "/work3/s212645/Spectral_Reconstruction/checkpoint/ldm/cond/logs/2024-03-24T19-57-56_hsi_autoencoder_kl_cond/checkpoints/last.ckpt"
        embed_dim: 64
        lossconfig:
          target: ldm.modules.losses.LPIPSWithDiscriminator
          params:
            disc_in_channels: 3
            disc_start: 50001
            kl_weight: 0.000001
            disc_weight: 0.5
            perceptual_weight: 0

        ddconfig:
          double_z: True
          z_channels: 64
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0

data:
  target: dataset.base.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 32
    train:
      target: dataset.datasets.TrainDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/
        crop_size: 256
        valid_ratio: 0.1
        test_ratio: 0.1
        aug: True
        datanames: ['ARAD/']
    validation:
      target: dataset.datasets.ValidDataset
      params:
        data_root: /work3/s212645/Spectral_Reconstruction/
        crop_size: 256
        valid_ratio: 0.1
        test_ratio: 0.1
        aug: True
        datanames: ['ARAD/']

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False


  trainer:
    benchmark: True